# Generated by Django 2.0.5 on 2018-05-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogebra_applet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geogebraapplet',
            name='archive',
            field=models.FileField(null=True, upload_to='geogebra_applet', verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='geogebraapplet',
            name='index_file',
            field=models.FileField(upload_to='geogebra_applet', verbose_name='Главный файл'),
        ),
    ]
